<?php
require_once '../includes/auth.php'; requireActiveUser(); requireTenantContext(); requireModulePermission('payments','view'); $tenantId=getCurrentTenantId();$rows=[];$q=$conn->query("SHOW TABLES LIKE 'payments'");
if($q&&$q->num_rows){$sql="SELECT p.*,i.invoice_number,c.customer_number,c.first_name,c.last_name FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id AND i.tenant_id=p.tenant_id LEFT JOIN customers c ON c.id=p.customer_id AND c.tenant_id=p.tenant_id";if($tenantId)$sql.=" WHERE p.tenant_id=".(int)$tenantId;$sql.=" ORDER BY p.id DESC LIMIT 500";$r=$conn->query($sql);if($r)while($x=$r->fetch_assoc())$rows[]=$x;}
$pageTitle='Payments';require_once '../includes/header.php';?>
<div class="dashboard-card"><div class="page-header"><div><h2>Payments</h2><p>Customer collections and payment records.</p></div><?php if(userCan('payments','create')): ?><a class="btn btn-primary" href="../payments/add.php">Record Payment</a><?php endif; ?></div><div class="table-responsive"><table><thead><tr><th>Reference</th><th>Invoice</th><th>Customer</th><th>Amount</th><th>Method</th><th>Date</th></tr></thead><tbody>
<?php foreach($rows as $x):?><tr><td><?=e($x['payment_number']??$x['reference']??$x['id'])?></td><td><?=e($x['invoice_number']??$x['invoice_id']??'')?></td><td><?=e(($x['customer_number']??'').' — '.trim(($x['first_name']??'').' '.($x['last_name']??'')))?></td><td><?=e(formatMoney($x['amount']??0))?></td><td><?=e($x['payment_method']??$x['method']??'')?></td><td><?=e($x['payment_date']??$x['created_at']??'')?></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6">No payments found.</td></tr><?php endif;?></tbody></table></div></div><?php require_once '../includes/footer.php';?>
<style>
/* Flexihub sleek black / blue module polish */
.page-content,.dashboard-card{color:#f8fafc}.page-header h1,.page-header h2{color:#f8fafc;letter-spacing:-.02em}.page-header p{color:#94a3b8!important}.card,.dashboard-card{background:linear-gradient(145deg,rgba(16,24,39,.96),rgba(11,17,27,.94))!important;border:1px solid rgba(148,163,184,.14)!important;box-shadow:0 16px 40px rgba(0,0,0,.22);border-radius:14px}.page-content input,.dashboard-card input{background:#0b111b!important;color:#f8fafc!important;border-color:rgba(148,163,184,.18)!important;border-radius:8px}.page-content input:focus,.dashboard-card input:focus{border-color:#3b82f6!important;box-shadow:0 0 0 3px rgba(37,99,235,.14);outline:none}.table,.dashboard-card table{width:100%;border-collapse:collapse}.table th,.dashboard-card th{background:#0b111b!important;color:#cbd5e1;border-color:rgba(148,163,184,.14)!important}.table td,.dashboard-card td{color:#e2e8f0;border-color:rgba(148,163,184,.14)!important}.table tbody tr:hover,.dashboard-card tbody tr:hover{background:rgba(37,99,235,.07)}.btn-primary{background:linear-gradient(135deg,#2563eb,#3b82f6)!important;color:#fff!important;border-color:transparent!important;box-shadow:0 8px 22px rgba(37,99,235,.18)}.btn-secondary{background:#172235!important;color:#cbd5e1!important;border:1px solid rgba(148,163,184,.14)!important}.btn-secondary:hover{background:#1d2b42!important;color:#fff!important}
</style>