<?php
require_once __DIR__ . '/../includes/auth.php';
requireLogin();
$tenantId=isTenantUser()?requireTenant():null;
$pageTitle='Customer Account';
$id=(int)($_GET['id']??0); if($id<=0) exit('Invalid customer.');
$stmt=$conn->prepare('SELECT * FROM customers WHERE id=?'.($tenantId?' AND tenant_id=?':'').' LIMIT 1');
if($tenantId)$stmt->bind_param('ii',$id,$tenantId);else$stmt->bind_param('i',$id);$stmt->execute();$customer=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$customer){http_response_code(404);exit('Customer not found.');}
$name=trim(($customer['first_name']??'').' '.($customer['last_name']??''));if($name==='')$name=$customer['customer_number']??('Customer #'.$id);
$accounts=[];$stmt=$conn->prepare('SELECT ia.*,ip.name plan_name,ip.price plan_price FROM internet_accounts ia LEFT JOIN internet_plans ip ON ip.id=ia.plan_id AND ip.tenant_id=ia.tenant_id WHERE ia.customer_id=?'.($tenantId?' AND ia.tenant_id=?':'').' ORDER BY ia.id DESC');if($tenantId)$stmt->bind_param('ii',$id,$tenantId);else$stmt->bind_param('i',$id);if($stmt->execute()){$r=$stmt->get_result();while($x=$r->fetch_assoc())$accounts[]=$x;}$stmt->close();
$invoices=[];$total=$paid=0.0;$stmt=$conn->prepare('SELECT i.*,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.invoice_id=i.id AND p.tenant_id=i.tenant_id),0) actual_paid FROM invoices i WHERE i.customer_id=?'.($tenantId?' AND i.tenant_id=?':'').' ORDER BY i.id DESC LIMIT 100');if($tenantId)$stmt->bind_param('ii',$id,$tenantId);else$stmt->bind_param('i',$id);if($stmt->execute()){$r=$stmt->get_result();while($x=$r->fetch_assoc()){$x['_total']=(float)($x['total_amount']??$x['total']??0);$x['_paid']=(float)$x['actual_paid'];$x['_balance']=max(0,$x['_total']-$x['_paid']);$total+=$x['_total'];$paid+=$x['_paid'];$invoices[]=$x;}}$stmt->close();
$payments=[];$stmt=$conn->prepare('SELECT p.*,i.invoice_number FROM payments p LEFT JOIN invoices i ON i.id=p.invoice_id AND i.tenant_id=p.tenant_id WHERE p.customer_id=?'.($tenantId?' AND p.tenant_id=?':'').' ORDER BY p.id DESC LIMIT 100');if($tenantId)$stmt->bind_param('ii',$id,$tenantId);else$stmt->bind_param('i',$id);if($stmt->execute()){$r=$stmt->get_result();while($x=$r->fetch_assoc())$payments[]=$x;}$stmt->close();
$active=0;foreach($accounts as $a){$s=strtolower((string)($a['status']??''));if($s==='active')$active++;}$outstanding=max(0,$total-$paid);
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><a href="index.php">← Customers</a><h1><?=e($name)?></h1><p><?=e($customer['customer_number']??'')?> · Customer account and service position</p></div><a class="btn btn-primary" href="../internet_accounts/add.php?customer_id=<?=$id?>">+ Internet Account</a></div>
<div class="summary"><div class="card identity"><small>CUSTOMER</small><h2><?=e($name)?></h2><p><?=e($customer['phone']??'—')?></p><p><?=e($customer['email']??'—')?></p></div><div class="stat"><small>ACTIVE SERVICES</small><strong><?=$active?></strong></div><div class="stat"><small>TOTAL INVOICED</small><strong><?=e(formatMoney($total))?></strong></div><div class="stat"><small>TOTAL PAID</small><strong><?=e(formatMoney($paid))?></strong></div><div class="stat danger"><small>OUTSTANDING</small><strong><?=e(formatMoney($outstanding))?></strong></div></div>
<div class="card section"><div class="head"><h2>Internet Services</h2><p>Plans, expiry dates and current status.</p></div><div class="table"><table><thead><tr><th>Account</th><th>Plan</th><th>Price</th><th>Expiry</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($accounts as $a):$s=strtolower((string)($a['status']??''));?><tr><td><b><?=e($a['account_number']??('#'.$a['id']))?></b></td><td><?=e($a['plan_name']??'—')?></td><td><?=e(formatMoney($a['plan_price']??0))?></td><td><?=e($a['expiry_date']??$a['billing_date']??'—')?></td><td><span class="status <?=e($s)"><?=e(ucfirst($s?:'unknown'))?></span></td><td><a class="btn btn-sm" href="../internet_accounts/edit.php?id=<?=(int)$a['id']?>">Manage</a></td></tr><?php endforeach;if(!$accounts):?><tr><td colspan="6" class="empty">No internet service accounts linked to this customer.</td></tr><?php endif;?></tbody></table></div></div>
<div class="card section"><div class="head"><h2>Invoices & Outstanding</h2><p>Balances use the actual payment ledger.</p></div><div class="table"><table><thead><tr><th>Invoice</th><th>Date</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($invoices as $x):?><tr><td><b><?=e($x['invoice_number']??$x['number']??$x['id'])?></b></td><td><?=e($x['invoice_date']??$x['date']??$x['created_at']??'—')?></td><td><?=e(formatMoney($x['_total']))?></td><td><?=e(formatMoney($x['_paid']))?></td><td><b><?=e(formatMoney($x['_balance']))?></b></td><td><?=e(ucfirst($x['status']??($x['_balance']<=0?'paid':'unpaid')))?></td></tr><?php endforeach;if(!$invoices):?><tr><td colspan="6" class="empty">No invoices found.</td></tr><?php endif;?></tbody></table></div></div>
<div class="card section"><div class="head"><h2>Payment History</h2><p>Collections received from this customer.</p></div><div class="table"><table><thead><tr><th>Reference</th><th>Invoice</th><th>Amount</th><th>Method</th><th>Date</th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?=e($p['payment_number']??$p['reference']??$p['id'])?></td><td><?=e($p['invoice_number']??$p['invoice_id']??'—')?></td><td><?=e(formatMoney($p['amount']??0))?></td><td><?=e($p['payment_method']??$p['method']??'—')?></td><td><?=e($p['payment_date']??$p['created_at']??'—')?></td></tr><?php endforeach;if(!$payments):?><tr><td colspan="5" class="empty">No payments found.</td></tr><?php endif;?></tbody></table></div></div></div>
<style>.main-content{padding:24px}.page-header{display:flex;justify-content:space-between;align-items:end;margin-bottom:22px}.page-header h1{margin:7px 0 3px;font-size:30px}.page-header p{margin:0;color:#6b7280}.page-header a:first-child{color:#6b7280;text-decoration:none}.summary{display:grid;grid-template-columns:2fr repeat(4,1fr);gap:14px;margin-bottom:20px}.card,.stat{background:#fff;border:1px solid #e5e7eb;border-radius:10px}.identity,.stat{padding:18px}.identity small,.stat small{color:#6b7280;font-size:11px;font-weight:700}.identity h2{margin:7px 0 10px}.identity p{margin:4px 0;color:#4b5563;font-size:13px}.stat strong{display:block;font-size:22px;margin-top:10px}.danger strong{color:#b91c1c}.section{overflow:hidden;margin-bottom:20px}.head{padding:17px 20px;border-bottom:1px solid #e5e7eb}.head h2{margin:0 0 4px;font-size:18px}.head p{margin:0;color:#6b7280;font-size:13px}.table{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{padding:12px 16px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:13px;white-space:nowrap}th{background:#f9fafb;color:#6b7280;font-size:11px;text-transform:uppercase}.empty{text-align:center;color:#6b7280;padding:30px}.btn{display:inline-block;padding:9px 13px;border-radius:6px;text-decoration:none;font-size:13px;font-weight:600}.btn-primary{background:#111827;color:#fff}.btn-sm{padding:6px 10px;background:#f3f4f6;color:#111827}.status{padding:5px 9px;border-radius:999px;background:#f3f4f6}.status.active{background:#dcfce7;color:#166534}.status.suspended{background:#fee2e2;color:#991b1b}.status.expired{background:#fef3c7;color:#92400e}@media(max-width:1100px){.summary{grid-template-columns:1fr 1fr}.identity{grid-column:1/-1}}@media(max-width:700px){.main-content{padding:15px}.page-header{align-items:start;flex-direction:column;gap:12px}.summary{grid-template-columns:1fr}}</style>
<?php require_once __DIR__.'/../includes/footer.php'; ?>