<?php
require_once __DIR__ . '/../includes/auth.php';
requireActiveUser();requireTenantContext();requireModulePermission('internet_plans','edit');
$tenantId=(int)getCurrentTenantId();$id=(int)($_GET['id']??$_POST['id']??0);if($id<1)redirect('index.php');
$s=$conn->prepare("SELECT * FROM internet_plans WHERE id=? AND tenant_id=? LIMIT 1");$s->bind_param('ii',$id,$tenantId);$s->execute();$existing=$s->get_result()->fetch_assoc();$s->close();if(!$existing)die('Internet plan not found.');
$values=['name'=>$existing['name']??'','price'=>$existing['price']??'','billing_cycle'=>$existing['billing_cycle']??'monthly','billing_days'=>$existing['billing_days']??'','download_speed'=>$existing['download_speed']??'','upload_speed'=>$existing['upload_speed']??'','description'=>$existing['description']??'','status'=>$existing['status']??'active'];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();foreach($values as $f=>$d)$values[$f]=trim((string)($_POST[$f]??$d));if($values['name']==='')$errors[]='Plan name is required.';if(!is_numeric($values['price'])||(float)$values['price']<0)$errors[]='Price must be valid.';if($values['billing_days']!==''&&(!ctype_digit($values['billing_days'])||(int)$values['billing_days']<1))$errors[]='Billing days must be positive.';if(!in_array($values['billing_cycle'],['daily','weekly','monthly','quarterly','yearly'],true))$errors[]='Invalid billing cycle.';if(!in_array($values['status'],['active','inactive'],true))$values['status']='active';
 if(!$errors){$s=$conn->prepare("UPDATE internet_plans SET name=?,price=?,billing_cycle=?,billing_days=?,download_speed=?,upload_speed=?,description=?,status=? WHERE id=? AND tenant_id=?");$s->bind_param('sdssssssii',$values['name'],$values['price'],$values['billing_cycle'],$values['billing_days'],$values['download_speed'],$values['upload_speed'],$values['description'],$values['status'],$id,$tenantId);if($s->execute()){ $s->close();logAudit('UPDATE','internet_plans','Internet plan updated.','internet_plan',$id,$existing,$values);redirect('index.php');}$errors[]='Unable to update the plan: '.$s->error;$s->close();}}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><h1>Edit Internet Plan</h1><p><?=e($existing['name']??'')?></p></div><a href="index.php" class="btn btn-light">Back</a></div><div class="dashboard-card"><?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post"><?=csrfField()?><input type="hidden" name="id" value="<?=$id?>"><div class="form-grid">
<div class="form-group"><label>Plan Name *</label><input name="name" value="<?=e($values['name'])?>" required></div><div class="form-group"><label>Price *</label><input type="number" step="0.01" min="0" name="price" value="<?=e($values['price'])?>" required></div>
<div class="form-group"><label>Billing Cycle</label><select name="billing_cycle"><?php foreach(['daily','weekly','monthly','quarterly','yearly'] as $x):?><option value="<?=$x?>" <?=$values['billing_cycle']===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach;?></select></div><div class="form-group"><label>Billing Days</label><input type="number" min="1" name="billing_days" value="<?=e($values['billing_days'])?>"></div>
<div class="form-group"><label>Download Speed</label><input name="download_speed" value="<?=e($values['download_speed'])?>"></div><div class="form-group"><label>Upload Speed</label><input name="upload_speed" value="<?=e($values['upload_speed'])?>"></div><div class="form-group"><label>Status</label><select name="status"><option value="active" <?=$values['status']==='active'?'selected':''?>>Active</option><option value="inactive" <?=$values['status']==='inactive'?'selected':''?>>Inactive</option></select></div></div>
<div class="form-group"><label>Description</label><textarea name="description" rows="4"><?=e($values['description'])?></textarea></div><button class="btn btn-primary">Update Plan</button> <a href="index.php" class="btn btn-light">Cancel</a></form></div></div><?php require_once __DIR__.'/../includes/footer.php';?>