-- Flexihub module foundation tables
CREATE TABLE IF NOT EXISTS network_sites (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(150) NOT NULL, location VARCHAR(255) NULL, status VARCHAR(30) NOT NULL DEFAULT 'active',
 description TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 KEY idx_network_sites_tenant(tenant_id), CONSTRAINT fk_network_sites_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS hotspot_packages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(150) NOT NULL, duration_minutes INT UNSIGNED NOT NULL DEFAULT 60, price DECIMAL(14,2) NOT NULL DEFAULT 0,
 status VARCHAR(30) NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 KEY idx_hotspot_packages_tenant(tenant_id), CONSTRAINT fk_hotspot_packages_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS hotspot_access_codes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 code VARCHAR(100) NOT NULL, package_id BIGINT UNSIGNED NULL, status VARCHAR(30) NOT NULL DEFAULT 'unused',
 expires_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_hotspot_code_tenant(tenant_id,code), KEY idx_hotspot_codes_tenant(tenant_id),
 CONSTRAINT fk_hotspot_codes_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS communication_templates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 name VARCHAR(150) NOT NULL, channel VARCHAR(30) NOT NULL DEFAULT 'sms', subject VARCHAR(255) NULL,
 message TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 KEY idx_comm_templates_tenant(tenant_id), CONSTRAINT fk_comm_templates_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tenant_wallets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 balance DECIMAL(14,2) NOT NULL DEFAULT 0, currency VARCHAR(10) NOT NULL DEFAULT 'KES',
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_tenant_wallet(tenant_id), CONSTRAINT fk_tenant_wallet_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS wallet_transactions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL,
 transaction_type VARCHAR(30) NOT NULL, amount DECIMAL(14,2) NOT NULL, reference VARCHAR(100) NULL,
 description VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 KEY idx_wallet_tx_tenant(tenant_id), CONSTRAINT fk_wallet_tx_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;