<?php
require_once '../includes/auth.php'; requireActiveUser(); requireTenantContext(); requireModulePermission('invoices','create');
global $conn; $tid=(int)getCurrentTenantId(); $errors=[]; $cols=[]; $r=$conn->query("SHOW COLUMNS FROM invoices"); if($r)while($x=$r->fetch_assoc())$cols[]=$x['Field'];
$customers=[];$q=$conn->prepare("SELECT id,customer_number,first_name,last_name FROM customers WHERE tenant_id=? ORDER BY first_name,last_name");if($q){$q->bind_param('i',$tid);$q->execute();$z=$q->get_result();while($x=$z->fetch_assoc())$customers[]=$x;$q->close();}
$v=['customer_id'=>'','amount'=>'','invoice_date'=>date('Y-m-d'),'due_date'=>date('Y-m-d'),'description'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();foreach($v as $k=>$d)$v[$k]=trim((string)($_POST[$k]??$d));$cid=(int)$v['customer_id'];$amount=(float)$v['amount'];if(!$cid||$amount<=0)$errors[]='Customer and a positive amount are required.';
if(!$errors){$fields=[];$vals=[];$types='';foreach(['customer_id','invoice_date','due_date','description'] as $f)if(in_array($f,$cols,true)&&$f!=='customer_id'||in_array($f,$cols,true)&&$f==='customer_id'){$fields[]=$f;$vals[]=$f==='customer_id'?$cid:$v[$f];$types.=$f==='customer_id'?'i':'s';}
foreach(['total_amount','amount','total'] as $f)if(in_array($f,$cols,true)){ $fields[]=$f;$vals[]=$amount;$types.='d';break;}if(in_array('tenant_id',$cols,true)){array_unshift($fields,'tenant_id');array_unshift($vals,$tid);$types='i'.$types;}
if(in_array('invoice_number',$cols,true)){array_splice($fields,1,0,'invoice_number');array_splice($vals,1,0,'INV-'.date('YmdHis').'-'.random_int(100,999));$types='is'.$types[1] . substr($types,2);}
if($fields){$ph=implode(',',array_fill(0,count($fields),'?'));$sql="INSERT INTO invoices(".implode(',',$fields).") VALUES($ph)";$q=$conn->prepare($sql);if($q){$q->bind_param($types,...$vals);if($q->execute()){redirect('index.php');}$errors[]=$q->error;$q->close();}}}}
require_once '../includes/header.php';require_once '../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><h1>Create Invoice</h1><p>Issue a tenant-scoped customer invoice.</p></div><a class="btn btn-secondary" href="index.php">Back</a></div><div class="card" style="padding:20px"><?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post"><?=csrfField()?><div class="form-grid"><label>Customer *<select name="customer_id" required><option value="">Select customer</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=$v['customer_id']==$c['id']?'selected':''?>><?=e($c['customer_number'].' — '.trim($c['first_name'].' '.$c['last_name']))?></option><?php endforeach;?></select></label><label>Amount *<input type="number" name="amount" step="0.01" min="0.01" value="<?=e($v['amount'])?>" required></label><label>Invoice Date<input type="date" name="invoice_date" value="<?=e($v['invoice_date'])?>"></label><label>Due Date<input type="date" name="due_date" value="<?=e($v['due_date'])?>"></label><label style="grid-column:1/-1">Description<textarea name="description"><?=e($v['description'])?></textarea></label></div><button class="btn btn-primary">Create Invoice</button></form></div></div><?php require_once '../includes/footer.php';?>