<?php
require_once '../includes/auth.php'; requireActiveUser(); requireTenantContext(); requireModulePermission('invoices','view'); $tenantId=(int)getCurrentTenantId(); if($tenantId<=0){http_response_code(403);exit('A valid tenant context is required.');} if(!flexihubTableHasColumn('invoices','tenant_id')||!flexihubTableHasColumn('customers','tenant_id')||!flexihubTableHasColumn('payments','tenant_id')){http_response_code(503);exit('Invoice tenant isolation is unavailable. Please contact the administrator.');} $rows=[];
$q=$conn->query("SHOW TABLES LIKE 'invoices'");
if($q&&$q->num_rows){$sql="SELECT i.*,c.customer_number,c.first_name,c.last_name,COALESCE((SELECT SUM(p.amount) FROM payments p WHERE p.invoice_id=i.id AND p.tenant_id=i.tenant_id),0) actual_paid FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id AND c.tenant_id=i.tenant_id";$sql.=" WHERE i.tenant_id=".(int)$tenantId;$sql.=" ORDER BY i.id DESC LIMIT 500";$r=$conn->query($sql);if($r)while($x=$r->fetch_assoc())$rows[]=$x;}
$pageTitle='Invoices';require_once '../includes/header.php';?>
<div class="dashboard-card"><div class="page-header"><div><h2>Invoices</h2><p>Customer billing and outstanding balances.</p></div><?php if(userCan('invoices','create')): ?><a class="btn btn-primary" href="add.php">Create Invoice</a><?php endif; ?></div><div class="table-responsive"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>
<?php foreach($rows as $x): $total=(float)($x['total_amount']??$x['total']??0);$paid=(float)($x['actual_paid']??0);?><tr><td><?=e($x['invoice_number']??$x['number']??$x['id'])?></td><td><?=e(($x['customer_number']??'').' — '.trim(($x['first_name']??'').' '.($x['last_name']??'')))?></td><td><?=e(formatMoney($total))?></td><td><?=e(formatMoney($paid))?></td><td><?=e(formatMoney(max(0,$total-$paid)))?></td><td><?=e($x['status']??'')?></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="6">No invoices found.</td></tr><?php endif;?></tbody></table></div></div><?php require_once '../includes/footer.php';?>
<style>
/* Flexihub sleek black / blue module polish */
.page-content,.dashboard-card{color:#f8fafc}.page-header h1,.page-header h2{color:#f8fafc;letter-spacing:-.02em}.page-header p{color:#94a3b8!important}.card,.dashboard-card{background:linear-gradient(145deg,rgba(16,24,39,.96),rgba(11,17,27,.94))!important;border:1px solid rgba(148,163,184,.14)!important;box-shadow:0 16px 40px rgba(0,0,0,.22);border-radius:14px}.page-content input,.dashboard-card input{background:#0b111b!important;color:#f8fafc!important;border-color:rgba(148,163,184,.18)!important;border-radius:8px}.page-content input:focus,.dashboard-card input:focus{border-color:#3b82f6!important;box-shadow:0 0 0 3px rgba(37,99,235,.14);outline:none}.table,.dashboard-card table{width:100%;border-collapse:collapse}.table th,.dashboard-card th{background:#0b111b!important;color:#cbd5e1;border-color:rgba(148,163,184,.14)!important}.table td,.dashboard-card td{color:#e2e8f0;border-color:rgba(148,163,184,.14)!important}.table tbody tr:hover,.dashboard-card tbody tr:hover{background:rgba(37,99,235,.07)}.btn-primary{background:linear-gradient(135deg,#2563eb,#3b82f6)!important;color:#fff!important;border-color:transparent!important;box-shadow:0 8px 22px rgba(37,99,235,.18)}.btn-secondary{background:#172235!important;color:#cbd5e1!important;border:1px solid rgba(148,163,184,.14)!important}.btn-secondary:hover{background:#1d2b42!important;color:#fff!important}
</style>