<?php
require_once __DIR__.'/../includes/auth.php';requireActiveUser();requireTenantContext();requireModulePermission('internet_accounts','create');
$tenantId=(int)getCurrentTenantId();$pageTitle='Create Customer Internet Account';$errors=[];
$customers=[];$s=$conn->prepare("SELECT id,customer_number,first_name,last_name FROM customers WHERE tenant_id=? ORDER BY first_name,last_name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$customers[]=$x;$s->close();
$plans=[];$s=$conn->prepare("SELECT id,name,price,billing_cycle,billing_days,download_speed,upload_speed FROM internet_plans WHERE tenant_id=? AND (status='active' OR status IS NULL) ORDER BY name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$plans[]=$x;$s->close();
$values=['customer_id'=>'','plan_id'=>'','username'=>'','status'=>'active','activation_date'=>date('Y-m-d')];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();foreach($values as $f=>$d)$values[$f]=trim((string)($_POST[$f]??$d));if((int)$values['customer_id']<1)$errors[]='Select a customer.';if((int)$values['plan_id']<1)$errors[]='Select an internet plan.';
$customerOk=false;$plan=null;foreach($customers as $c)if((int)$c['id']===(int)$values['customer_id'])$customerOk=true;foreach($plans as $p)if((int)$p['id']===(int)$values['plan_id'])$plan=$p;if(!$customerOk)$errors[]='Selected customer is invalid.';if(!$plan)$errors[]='Selected plan is invalid.';
if(!in_array($values['status'],['active','pending','suspended','inactive'],true))$values['status']='active';
if(!$errors){$expiry=calculateAccountExpiry($values['activation_date']?:date('Y-m-d'),$plan);$accountNo=generateInternetAccountNumber();$s=$conn->prepare("INSERT INTO internet_accounts (tenant_id,account_number,customer_id,plan_id,username,status,activation_date,expiry_date,billing_date) VALUES (?,?,?,?,?,?,?,?,?)");if($s){$s->bind_param('isiisssss',$tenantId,$accountNo,$values['customer_id'],$values['plan_id'],$values['username'],$values['status'],$values['activation_date'],$expiry,$expiry);if($s->execute()){$id=$s->insert_id;$s->close();logAudit('CREATE','internet_accounts','Customer internet account created.','internet_account',$id,null,$values);redirect('index.php');}$errors[]='Unable to create account: '.$s->error;$s->close();}else$errors[]='Unable to prepare account: '.$conn->error;}}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><h1>Create Customer Internet Account</h1><p>Assign an active internet plan to a registered customer.</p></div><a href="index.php" class="btn btn-light">Back</a></div><div class="dashboard-card"><?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post"><?=csrfField()?><div class="form-grid">
<div class="form-group"><label>Customer *</label><select name="customer_id" required><option value="">Select customer</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=$values['customer_id']==$c['id']?'selected':''?>><?=e($c['customer_number'].' — '.trim($c['first_name'].' '.$c['last_name']))?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Internet Plan *</label><select name="plan_id" required><option value="">Select plan</option><?php foreach($plans as $p):?><option value="<?=$p['id']?>" <?=$values['plan_id']==$p['id']?'selected':''?>><?=e($p['name'].' — '.formatMoney($p['price']??0))?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Username</label><input name="username" value="<?=e($values['username'])?>"></div><div class="form-group"><label>Activation Date</label><input type="date" name="activation_date" value="<?=e($values['activation_date'])?>"></div>
<div class="form-group"><label>Status</label><select name="status"><?php foreach(['active','pending','suspended','inactive'] as $x):?><option value="<?=$x?>" <?=$values['status']===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach;?></select></div></div>
<div style="margin-top:20px"><button class="btn btn-primary">Create Account</button> <a href="index.php" class="btn btn-light">Cancel</a></div></form></div></div><?php require_once __DIR__.'/../includes/footer.php';?>