<?php
require_once __DIR__.'/../includes/auth.php';requireActiveUser();requireTenantContext();requireModulePermission('internet_accounts','edit');
$tenantId=(int)getCurrentTenantId();$id=(int)($_GET['id']??$_POST['id']??0);if($id<1)redirect('index.php');
$s=$conn->prepare("SELECT * FROM internet_accounts WHERE id=? AND tenant_id=? LIMIT 1");$s->bind_param('ii',$id,$tenantId);$s->execute();$existing=$s->get_result()->fetch_assoc();$s->close();if(!$existing)die('Internet account not found.');
$customers=[];$s=$conn->prepare("SELECT id,customer_number,first_name,last_name FROM customers WHERE tenant_id=? ORDER BY first_name,last_name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$customers[]=$x;$s->close();
$plans=[];$s=$conn->prepare("SELECT id,name,price,billing_cycle,billing_days FROM internet_plans WHERE tenant_id=? ORDER BY name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$plans[]=$x;$s->close();
$values=['customer_id'=>$existing['customer_id']??'','plan_id'=>$existing['plan_id']??'','username'=>$existing['username']??'','status'=>$existing['status']??'active','activation_date'=>$existing['activation_date']??date('Y-m-d'),'expiry_date'=>$existing['expiry_date']??''];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();foreach($values as $f=>$d)$values[$f]=trim((string)($_POST[$f]??$d));$validC=$validP=false;$plan=null;foreach($customers as $c)if((int)$c['id']===(int)$values['customer_id'])$validC=true;foreach($plans as $p)if((int)$p['id']===(int)$values['plan_id']){$validP=true;$plan=$p;}if(!$validC)$errors[]='Selected customer is invalid.';if(!$validP)$errors[]='Selected plan is invalid.';if(!in_array($values['status'],['active','pending','suspended','expired','inactive'],true))$errors[]='Invalid status.';
if(!$errors){$expiry=calculateAccountExpiry($values['activation_date']?:date('Y-m-d'),$plan);$s=$conn->prepare("UPDATE internet_accounts SET customer_id=?,plan_id=?,username=?,status=?,activation_date=?,expiry_date=?,billing_date=? WHERE id=? AND tenant_id=?");$s->bind_param('iisssssii',$values['customer_id'],$values['plan_id'],$values['username'],$values['status'],$values['activation_date'],$expiry,$expiry,$id,$tenantId);if($s->execute()){$s->close();logAudit('UPDATE','internet_accounts','Customer internet account updated.','internet_account',$id,$existing,$values);redirect('index.php');}$errors[]='Unable to update account: '.$s->error;$s->close();}}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><h1>Edit Customer Internet Account</h1><p><?=e($existing['account_number']??'')?></p></div><a href="index.php" class="btn btn-light">Back</a></div><div class="dashboard-card"><?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post"><?=csrfField()?><input type="hidden" name="id" value="<?=$id?>"><div class="form-grid">
<div class="form-group"><label>Customer *</label><select name="customer_id" required><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=$values['customer_id']==$c['id']?'selected':''?>><?=e($c['customer_number'].' — '.trim($c['first_name'].' '.$c['last_name']))?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Internet Plan *</label><select name="plan_id" required><?php foreach($plans as $p):?><option value="<?=$p['id']?>" <?=$values['plan_id']==$p['id']?'selected':''?>><?=e($p['name'].' — '.formatMoney($p['price']??0))?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Username</label><input name="username" value="<?=e($values['username'])?>"></div><div class="form-group"><label>Activation Date</label><input type="date" name="activation_date" value="<?=e($values['activation_date'])?>"></div>
<div class="form-group"><label>Status</label><select name="status"><?php foreach(['active','pending','suspended','expired','inactive'] as $x):?><option value="<?=$x?>" <?=$values['status']===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach;?></select></div></div>
<div style="margin-top:20px"><button class="btn btn-primary">Update Account</button> <a href="index.php" class="btn btn-light">Cancel</a></div></form></div></div><?php require_once __DIR__.'/../includes/footer.php';?>