<?php
require_once '../includes/auth.php';
requireLogin(); $tenantId=requireTenant(); $pageTitle='Edit Customer Internet Account';
function ec(){global $conn;$a=[];$r=$conn->query("SHOW COLUMNS FROM internet_accounts");if($r)while($x=$r->fetch_assoc())$a[]=$x['Field'];return $a;}
$cols=ec();$id=(int)($_GET['id']??$_POST['id']??0);if($id<1)redirect('index.php');
$sql='SELECT * FROM internet_accounts WHERE id=?';$types='i';$p=[$id];if(in_array('tenant_id',$cols,true)){$sql.=' AND tenant_id=?';$types.='i';$p[]=$tenantId;}$sql.=' LIMIT 1';$s=$conn->prepare($sql);$b=[$types];foreach($p as $k=>$v)$b[]=&$p[$k];call_user_func_array([$s,'bind_param'],$b);$s->execute();$a=$s->get_result()->fetch_assoc();$s->close();if(!$a)die('Internet account not found.');
$customers=[];$s=$conn->prepare("SELECT id,customer_number,first_name,last_name FROM customers WHERE tenant_id=? ORDER BY first_name,last_name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$customers[]=$x;$s->close();
$plans=[];$s=$conn->prepare("SELECT * FROM internet_plans WHERE tenant_id=? ORDER BY name");$s->bind_param('i',$tenantId);$s->execute();$r=$s->get_result();while($x=$r->fetch_assoc())$plans[]=$x;$s->close();
$values=['customer_id'=>$a['customer_id']??'','plan_id'=>$a['plan_id']??'','connection_type'=>$a['connection_type']??'pppoe','username'=>$a['username']??'','status'=>$a['status']??'active','activation_date'=>$a['activation_date']??date('Y-m-d'),'expiry_date'=>$a['expiry_date']??'','billing_date'=>$a['billing_date']??''];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();foreach($values as $f=>$d)$values[$f]=trim((string)($_POST[$f]??$d));if((int)$values['customer_id']<1|| (int)$values['plan_id']<1)$errors[]='Customer and plan are required.';
if(!$errors){$validCustomer=false;$validPlan=false;foreach($customers as $c)if((int)$c['id']===(int)$values['customer_id'])$validCustomer=true;foreach($plans as $p)if((int)$p['id']===(int)$values['plan_id'])$validPlan=true;if(!$validCustomer)$errors[]='Selected customer is invalid.';if(!$validPlan)$errors[]='Selected plan is invalid.';}if(!$errors){$allowed=['customer_id','plan_id','username','status','activation_date','expiry_date','billing_date'];$u=[];foreach($allowed as $f)if(in_array($f,$cols,true))$u[$f]=$values[$f];$set=[];$bv=[];$bt='';foreach($u as $f=>$v){$set[]=$f.'=?';$bt.=in_array($f,['customer_id','plan_id'],true)?'i':'s';$bv[]=$v;}$sql='UPDATE internet_accounts SET '.implode(',',$set).' WHERE id=?';$bt.='i';$bv[]=$id;if(in_array('tenant_id',$cols,true)){$sql.=' AND tenant_id=?';$bt.='i';$bv[]=$tenantId;}$s=$conn->prepare($sql);$b=[$bt];foreach($bv as $k=>$v)$b[]=&$bv[$k];call_user_func_array([$s,'bind_param'],$b);if($s->execute()){ $s->close();redirect('index.php');}$errors[]='Unable to update account: '.$s->error;$s->close();}}
require_once '../includes/header.php';?><div class="dashboard-card"><?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><form method="post"><?=csrfField()?><input type="hidden" name="id" value="<?=$id?>"><div class="form-grid">
<div class="form-group"><label>Customer *</label><select name="customer_id" required><?php foreach($customers as $c):?><option value="<?=$c['id']?>" <?=$values['customer_id']==$c['id']?'selected':''?>><?=e($c['customer_number'].' — '.trim($c['first_name'].' '.$c['last_name']))?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Internet Plan *</label><select name="plan_id" required><?php foreach($plans as $p):?><option value="<?=$p['id']?>" <?=$values['plan_id']==$p['id']?'selected':''?>><?=e($p['name'].' — '.formatMoney($p['price']??0))?></option><?php endforeach;?></select></div>
<?php if(in_array('connection_type',$cols,true)):?><div class="form-group"><label>Connection Type</label><select name="connection_type"><option value="pppoe" <?=$values['connection_type']==='pppoe'?'selected':''?>>PPPoE</option><option value="hotspot" <?=$values['connection_type']==='hotspot'?'selected':''?>>Hotspot</option><option value="static" <?=$values['connection_type']==='static'?'selected':''?>>Static / Routed</option><option value="other" <?=$values['connection_type']==='other'?'selected':''?>>Other</option></select></div><?php endif;?><?php if(in_array('username',$cols,true)):?><div class="form-group"><label>Username</label><input name="username" value="<?=e($values['username'])?>"></div><?php endif;?>
<?php if(in_array('activation_date',$cols,true)):?><div class="form-group"><label>Activation Date</label><input type="date" name="activation_date" value="<?=e($values['activation_date'])?>"></div><?php endif;?>
<?php if(in_array('expiry_date',$cols,true)):?><div class="form-group"><label>Expiry Date</label><input type="date" name="expiry_date" value="<?=e($values['expiry_date'])?>"></div><?php endif;?>
<?php if(in_array('status',$cols,true)):?><div class="form-group"><label>Status</label><select name="status"><?php foreach(['active','pending','suspended','expired','inactive'] as $x):?><option value="<?=$x?>" <?=$values['status']===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach;?></select></div><?php endif;?>
</div><div style="margin-top:20px;"><button class="btn btn-primary">Update Account</button> <a href="index.php" class="btn btn-light">Cancel</a></div></form></div><?php require_once '../includes/footer.php';?>