<?php
require_once __DIR__.'/../includes/auth.php';requireActiveUser();requireTenantContext();requireModulePermission('internet_accounts','view');
$tenantId=(int)getCurrentTenantId();$pageTitle='Customer Internet Accounts';$q=trim($_GET['q']??'');$status=trim($_GET['status']??'');
$where=['ia.tenant_id=?','c.tenant_id=?'];$params=[$tenantId,$tenantId];$types='ii';
if($q!==''){ $where[]='(c.customer_number LIKE ? OR c.first_name LIKE ? OR c.last_name LIKE ? OR ia.account_number LIKE ? OR ia.username LIKE ?)';$v='%'.$q.'%';for($i=0;$i<5;$i++){$params[]=$v;$types.='s';}}
if(in_array($status,['active','suspended','expired','pending','inactive'],true)){$where[]='ia.status=?';$params[]=$status;$types.='s';}
$sql="SELECT ia.*,c.customer_number,c.first_name,c.last_name,ip.name plan_name,ip.price plan_price FROM internet_accounts ia JOIN customers c ON c.id=ia.customer_id LEFT JOIN internet_plans ip ON ip.id=ia.plan_id AND ip.tenant_id=ia.tenant_id WHERE ".implode(' AND ',$where)." ORDER BY ia.id DESC LIMIT 200";
$stmt=$conn->prepare($sql);$accounts=[];if($stmt){$b=[$types];foreach($params as $k=>$v)$b[]=&$params[$k];call_user_func_array([$stmt,'bind_param'],$b);if($stmt->execute()){$r=$stmt->get_result();while($x=$r->fetch_assoc())$accounts[]=$x;}$stmt->close();}
require_once __DIR__.'/../includes/header.php';require_once __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="page-header"><div><h1>Customer Internet Accounts</h1><p>Connect customers to plans and control service status.</p></div><?php if(userCan('internet_accounts','create')):?><a href="add.php" class="btn btn-primary">+ Create Customer Account</a><?php endif;?></div>
<div class="dashboard-card" style="margin-bottom:20px"><form method="get" style="display:flex;gap:10px;align-items:end;flex-wrap:wrap"><div><label>Search</label><input name="q" value="<?=e($q)?>" placeholder="Customer, account or username"></div><div><label>Status</label><select name="status"><option value="">All</option><?php foreach(['active','suspended','expired','pending','inactive'] as $s):?><option value="<?=$s?>" <?=$status===$s?'selected':''?>><?=ucfirst($s)?></option><?php endforeach;?></select></div><button class="btn btn-secondary">Filter</button><a href="index.php" class="btn btn-light">Reset</a></form></div>
<div class="dashboard-card"><div class="table-responsive"><table class="data-table" style="width:100%"><thead><tr><th>Account</th><th>Customer</th><th>Plan</th><th>Price</th><th>Expiry</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php if(!$accounts):?><tr><td colspan="7">No customer internet accounts found.</td></tr><?php else:foreach($accounts as $a):$computed=getInternetAccountStatus($a);?><tr><td><strong><?=e($a['account_number']??('#'.$a['id']))?></strong><?php if(!empty($a['username'])):?><small><?=e($a['username'])?></small><?php endif;?></td><td><?=e(trim(($a['first_name']??'').' '.($a['last_name']??'')))?><small><?=e($a['customer_number']??'')?></small></td><td><?=e($a['plan_name']??'—')?></td><td><?=e(formatMoney($a['plan_price']??0))?></td><td><?=e($a['expiry_date']??'—')?></td><td><?=e(ucfirst($computed))?></td><td><?php if(userCan('internet_accounts','edit')):?><a class="btn btn-sm" href="edit.php?id=<?=(int)$a['id']?>">Edit</a><?php endif;?></td></tr><?php endforeach;endif;?>
</tbody></table></div></div></div><?php require_once __DIR__.'/../includes/footer.php';?>