<?php
require_once '../includes/auth.php';require_once '../includes/functions.php';requireActiveUser();requireTenantContext();requireModulePermission('network','edit');global $conn;
$id=(int)($_GET['id']??0);if(!$id)die('Invalid router.');$cols=[];$res=$conn->query("SHOW COLUMNS FROM mikrotik_routers");if(!$res)die('Unable to read MikroTik router configuration.');while($row=$res->fetch_assoc())$cols[]=$row['Field'];$has=fn($c)=>in_array($c,$cols,true);$tenantId=(int)getCurrentTenantId();if($tenantId<=0||!$has('tenant_id')){http_response_code(503);die('Tenant-scoped router access is unavailable for this session or database schema.');}$where='id = ? AND tenant_id = ?';$params=[$id,$tenantId];$types='ii';$stmt=$conn->prepare("SELECT * FROM mikrotik_routers WHERE $where LIMIT 1");$stmt->bind_param($types,...$params);$stmt->execute();$router=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$router)die('Router not found.');
$host=$has('host')?($router['host']??''):($has('ip_address')?($router['ip_address']??''):($router['ip']??''));$port=$has('api_port')?($router['api_port']??8728):($router['port']??8728);$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){requireCsrf();$hotspotLoginUrl=trim($_POST['hotspot_login_url']??'');if($hotspotLoginUrl!==''&&!filter_var($hotspotLoginUrl,FILTER_VALIDATE_URL))$errors[]='Hotspot login URL must be a valid URL.';$fields=[];$vals=[];$types='';$map=['name'=>trim($_POST['name']??''),'router_name'=>trim($_POST['name']??''),'host'=>trim($_POST['host']??$host),'ip_address'=>trim($_POST['host']??$host),'ip'=>trim($_POST['host']??$host),'username'=>trim($_POST['username']??''),'api_port'=>(int)($_POST['api_port']??$port),'port'=>(int)($_POST['api_port']??$port),'hotspot_login_url'=>$hotspotLoginUrl,'status'=>$_POST['status']??'active','description'=>trim($_POST['description']??'')];foreach($map as $c=>$v)if($has($c)){$fields[]=$c.' = ?';$vals[]=$v;$types.=is_int($v)?'i':'s';}if($has('password')&&trim($_POST['password']??'')!==''){$fields[]='password = ?';$vals[]=trim($_POST['password']);$types.='s';}if(!$errors&&$fields){$vals[]=$id;$types.='i';$sql="UPDATE mikrotik_routers SET ".implode(',',$fields)." WHERE id = ?";$sql.=' AND tenant_id = ?';$vals[]=$tenantId;$types.='i';$u=$conn->prepare($sql);if($u){$u->bind_param($types,...$vals);if($u->execute())redirect('index.php');$errors[]=$u->error;$u->close();}}}
?>
<?php require '../includes/header.php';?><div class="page-content"><div class="page-header"><div><h1>Edit MikroTik Router</h1><p>Update router connection details.</p></div><a class="btn btn-secondary" href="index.php">Back</a></div>
<?php if($errors):?><div class="alert alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><div class="card" style="max-width:760px;padding:22px"><form method="post"><?=csrfField()?><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">
<?php if($has('name')||$has('router_name')):?><label>Router Name<input name="name" required value="<?=e($_POST['name']??($router['name']??$router['router_name']??''))?>"></label><?php endif;?>
<?php if($has('host')||$has('ip_address')||$has('ip')):?><label>Host / IP<input name="host" required value="<?=e($_POST['host']??$host)?>"></label><?php endif;?>
<?php if($has('api_port')||$has('port')):?><label>API Port<input type="number" name="api_port" value="<?=e($_POST['api_port']??$port)?>"></label><?php endif;?>
<?php if($has('hotspot_login_url')):?><label>Hotspot Login URL<input name="hotspot_login_url" value="<?=e($_POST['hotspot_login_url']??($router['hotspot_login_url']??''))?>" placeholder="http://192.168.88.1/login"><small>Client-reachable MikroTik HotSpot login endpoint.</small></label><?php endif;?>
<?php if($has('username')):?><label>Username<input name="username" value="<?=e($_POST['username']??($router['username']??''))?>"></label><?php endif;?>
<?php if($has('password')):?><label>New Password<input type="password" name="password" autocomplete="new-password" placeholder="Leave blank to keep current"></label><?php endif;?>
<?php if($has('status')):?><label>Status<select name="status"><?php foreach(['active','inactive','disabled'] as $v):?><option value="<?=$v?>" <?=strtolower($_POST['status']??($router['status']??''))===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><?php endif;?></div>
<?php if($has('description')):?><label>Description<textarea name="description"><?=e($_POST['description']??($router['description']??''))?></textarea></label><?php endif;?><div style="margin-top:18px"><button class="btn btn-primary">Update Router</button></div></form></div></div><?php require '../includes/footer.php';?>