<?php
require_once '../includes/auth.php';
requireActiveUser();
requireTenantContext();
requireModulePermission('communication','view');
global $conn;
$tenantId=(int)getCurrentTenantId(); $userId=(int)($_SESSION['user_id']??0); $canEdit=true;
try{requireModulePermission('communication','edit');}catch(Throwable $e){$canEdit=false;}
if(empty($_SESSION['chat_csrf']))$_SESSION['chat_csrf']=bin2hex(random_bytes(32)); $csrf=$_SESSION['chat_csrf']; $error=''; $flash='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!$canEdit)$error='You do not have permission to modify conversations.';
 elseif(!hash_equals($csrf,(string)($_POST['csrf_token']??'')))$error='Security token expired. Reload and try again.';
 else{
  $action=(string)($_POST['action']??'');
  if($action==='create'){
   $cid=(int)($_POST['customer_id']??0); $channel=trim((string)($_POST['channel']??'web')); $subject=trim((string)($_POST['subject']??''));
   if(!in_array($channel,['web','portal','whatsapp','sms','phone','other'],true))$channel='web'; $valid=true;
   if($cid){$v=$conn->prepare("SELECT id FROM customers WHERE id=? AND tenant_id=? LIMIT 1");if(!$v)$valid=false;else{$v->bind_param('ii',$cid,$tenantId);$v->execute();$valid=(bool)$v->get_result()->fetch_assoc();$v->close();}}
   if(!$valid)$error='Selected customer was not found in this tenant.';
   else{$s=$conn->prepare("INSERT INTO customer_chats(tenant_id,customer_id,channel,subject,status,assigned_user_id) VALUES(?,?,?,?,?,?)");if($s){$status='open';$assigned=$userId?:null;$s->bind_param('iisssi',$tenantId,$cid,$channel,$subject,$status,$assigned);if($s->execute()){$id=(int)$s->insert_id;$s->close();header("Location: customer_chat.php?id=".$id);exit;}$s->close();}$error='Unable to create conversation.';}
  }elseif($action==='send'){
   $chat=(int)($_POST['chat_id']??0);$message=trim((string)($_POST['message']??''));$ok=false;
   $v=$conn->prepare("SELECT id FROM customer_chats WHERE id=? AND tenant_id=? LIMIT 1");if($v){$v->bind_param('ii',$chat,$tenantId);$v->execute();$ok=(bool)$v->get_result()->fetch_assoc();$v->close();}
   if(!$ok)$error='Conversation not found.';elseif($message==='')$error='Enter a message.';
   else{$s=$conn->prepare("INSERT INTO customer_chat_messages(tenant_id,chat_id,sender_type,sender_id,message) VALUES(?,?,?,?,?)");if($s){$type='staff';$s->bind_param('iisis',$tenantId,$chat,$type,$userId,$message);if($s->execute()){$s->close();$u=$conn->prepare("UPDATE customer_chats SET status='open',last_message_at=NOW(),updated_at=NOW() WHERE id=? AND tenant_id=?");if($u){$u->bind_param('ii',$chat,$tenantId);$u->execute();$u->close();}header("Location: customer_chat.php?id=".$chat);exit;}$s->close();}$error='Unable to send message.';}
  }elseif($action==='close'){
   $chat=(int)($_POST['chat_id']??0);$s=$conn->prepare("UPDATE customer_chats SET status='closed',updated_at=NOW() WHERE id=? AND tenant_id=?");if($s){$s->bind_param('ii',$chat,$tenantId);$s->execute();$s->close();$flash='Conversation closed.';}else$error='Unable to close conversation.';
  }
 }
}
$rows=[];$q=$conn->prepare("SELECT c.*,cu.first_name,cu.last_name,cu.customer_number FROM customer_chats c LEFT JOIN customers cu ON cu.id=c.customer_id AND cu.tenant_id=c.tenant_id WHERE c.tenant_id=? ORDER BY COALESCE(c.last_message_at,c.created_at) DESC LIMIT 200");if($q){$q->bind_param('i',$tenantId);$q->execute();$z=$q->get_result();while($r=$z->fetch_assoc())$rows[]=$r;$q->close();}
$selectedId=(int)($_GET['id']??0);$selected=null;foreach($rows as $r)if((int)$r['id']===$selectedId)$selected=$r;
$messages=[];if($selected){$q=$conn->prepare("SELECT * FROM customer_chat_messages WHERE tenant_id=? AND chat_id=? ORDER BY id ASC LIMIT 300");if($q){$q->bind_param('ii',$tenantId,$selectedId);$q->execute();$z=$q->get_result();while($r=$z->fetch_assoc())$messages[]=$r;$q->close();}}
$pageTitle='Customer Chat';require_once '../includes/header.php';?>
<div class="dashboard-card chat-center"><div class="page-header chat-head"><div><span class="kicker">CUSTOMER SERVICE</span><h2>Customer Chat</h2><p>Tenant-scoped support conversations and staff replies.</p></div><?php if($canEdit):?><button class="btn btn-primary" onclick="document.getElementById('newChat').showModal()">+ New Conversation</button><?php endif;?></div>
<?php if($flash):?><div class="notice ok"><?=e($flash)?></div><?php endif;?><?php if($error):?><div class="notice err"><?=e($error)?></div><?php endif;?>
<div class="chat-grid"><aside class="chat-list"><div class="list-title"><b>Conversations</b><span><?=count($rows)?></span></div><?php foreach($rows as $r):$name=trim(($r['first_name']??'').' '.($r['last_name']??''));if($name==='')$name=$r['customer_number']??'Unlinked customer';?><a class="chat-item <?=((int)$r['id']===$selectedId?'active':'')?>" href="customer_chat.php?id=<?=(int)$r['id']?>"><div><b><?=e($name)?></b><small><?=e($r['subject']?:'General support')?></small></div><em><?=e(ucfirst($r['status']))?></em></a><?php endforeach;?><?php if(!$rows):?><div class="empty">No conversations yet.</div><?php endif;?></aside>
<section class="thread"><?php if($selected):$name=trim(($selected['first_name']??'').' '.($selected['last_name']??''));if($name==='')$name=$selected['customer_number']??'Unlinked customer';?><div class="thread-head"><div><b><?=e($name)?></b><small><?=e($selected['subject']?:'General support')?> · <?=e(ucfirst($selected['channel']))?></small></div><?php if($canEdit&&$selected['status']!=='closed'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="action" value="close"><input type="hidden" name="chat_id" value="<?=$selectedId?>"><button class="btn btn-secondary">Close</button></form><?php endif;?></div><div class="messages"><?php foreach($messages as $m):?><div class="msg <?=$m['sender_type']==='staff'?'staff':''?>"><small><?=e(ucfirst($m['sender_type']))?> · <?=e($m['created_at'])?></small><div><?=nl2br(e($m['message']))?></div></div><?php endforeach;?><?php if(!$messages):?><div class="empty">No messages yet.</div><?php endif;?></div><?php if($canEdit&&$selected['status']!=='closed'):?><form method="post" class="reply"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="action" value="send"><input type="hidden" name="chat_id" value="<?=$selectedId?>"><textarea name="message" rows="3" required placeholder="Write a response..."></textarea><button class="btn btn-primary">Send Reply</button></form><?php endif;?><?php else:?><div class="empty focus"><h3>Select a conversation</h3><p>Choose a conversation or create a new one.</p></div><?php endif;?></section></div></div>
<?php if($canEdit):?><dialog id="newChat"><form method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="action" value="create"><h3>New Conversation</h3><label>Customer ID<input class="form-control" type="number" name="customer_id" min="1" placeholder="Optional"></label><label>Channel<select class="form-control" name="channel"><option>web</option><option>portal</option><option>whatsapp</option><option>sms</option><option>phone</option><option>other</option></select></label><label>Subject<input class="form-control" name="subject" maxlength="200" placeholder="e.g. Internet service issue"></label><div class="actions"><button type="button" class="btn btn-secondary" onclick="newChat.close()">Cancel</button><button class="btn btn-primary">Create</button></div></form></dialog><?php endif;?>
<style>.chat-center{padding:24px;background:linear-gradient(145deg,#101827,#0b111b);color:#f8fafc}.chat-head{display:flex;justify-content:space-between;gap:15px;align-items:center}.kicker{font-size:11px;font-weight:800;letter-spacing:.14em;color:#60a5fa}.chat-head h2{margin:6px 0}.chat-head p{margin:0;color:#94a3b8}.chat-grid{display:grid;grid-template-columns:320px 1fr;min-height:600px;border:1px solid #1e293b;border-radius:14px;overflow:hidden;background:#080d15}.chat-list{border-right:1px solid #1e293b;overflow:auto}.list-title{display:flex;justify-content:space-between;padding:15px;border-bottom:1px solid #1e293b}.list-title span{color:#60a5fa}.chat-item{display:flex;justify-content:space-between;gap:8px;padding:13px 14px;color:#e2e8f0;text-decoration:none;border-bottom:1px solid #172033}.chat-item:hover,.chat-item.active{background:rgba(37,99,235,.13)}.chat-item b,.chat-item small{display:block}.chat-item small{color:#94a3b8;margin-top:4px}.chat-item em{font-style:normal;font-size:10px;color:#4ade80}.thread{display:flex;flex-direction:column;min-width:0}.thread-head{display:flex;justify-content:space-between;padding:15px;border-bottom:1px solid #1e293b}.thread-head b,.thread-head small{display:block}.thread-head small{color:#94a3b8;margin-top:4px}.messages{flex:1;padding:20px;overflow:auto}.msg{max-width:75%;margin:0 0 14px}.msg.staff{margin-left:auto}.msg small{display:block;color:#64748b;margin-bottom:4px;font-size:10px}.msg div{background:#172235;padding:11px 13px;border-radius:12px;line-height:1.5}.msg.staff div{background:#1d4ed8;color:white}.reply{display:grid;grid-template-columns:1fr auto;gap:10px;padding:15px;border-top:1px solid #1e293b}.reply textarea,.form-control{background:#0a101a;color:#f8fafc;border:1px solid #263449;border-radius:8px;padding:10px;box-sizing:border-box;width:100%}.empty{text-align:center;padding:30px;color:#64748b}.focus{margin:auto}.notice{padding:10px 13px;margin-bottom:12px;border-radius:8px}.notice.ok{background:rgba(34,197,94,.1);color:#4ade80}.notice.err{background:rgba(244,63,94,.1);color:#fb7185}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:9px 14px;border-radius:8px;border:1px solid transparent;font-weight:700;cursor:pointer;text-decoration:none}.btn-primary{background:#2563eb;color:white}.btn-secondary{background:#172235;color:#cbd5e1;border-color:#263449}dialog{background:#101827;color:#f8fafc;border:1px solid #263449;border-radius:12px;padding:20px;width:min(440px,90vw)}dialog form{display:grid;gap:12px}dialog label{display:grid;gap:6px;color:#cbd5e1}.actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:800px){.chat-grid{grid-template-columns:1fr}.chat-list{max-height:260px;border-right:0;border-bottom:1px solid #1e293b}.chat-head{align-items:flex-start;flex-direction:column}.reply{grid-template-columns:1fr}}</style>
<?php require_once '../includes/footer.php';?>